"""
HTML Document Service

Converts frontend-rendered HTML directly to Word/PDF documents.
This ensures 100% consistency between frontend preview and downloaded documents.
"""

from typing import Dict, Any, Tuple
import logging
import tempfile
import os
from pathlib import Path
from datetime import datetime
import re
from html import unescape

logger = logging.getLogger(__name__)

class HTMLDocumentService:
    """Service for converting frontend HTML captures to Word/PDF documents."""
    
    def __init__(self):
        """Initialize the HTML document service."""
        self.temp_dir = tempfile.gettempdir()
        logger.info("HTMLDocumentService initialized")
    
    def generate_document_from_html(self, html_content: str, output_format: str = 'pdf', 
                                  metadata: Dict[str, Any] = None) -> Tuple[bool, Dict[str, Any]]:
        """
        Generate a downloadable document from frontend HTML capture.
        
        Args:
            html_content: The HTML content captured from frontend
            output_format: Output format ('pdf' or 'word')
            metadata: Metadata about the analysis (job_from, analysis_mode, etc.)
            
        Returns:
            Tuple of (success, result_data)
        """
        try:
            if metadata is None:
                metadata = {}
            
            # Clean and prepare HTML for document conversion
            cleaned_html = self._prepare_html_for_document(html_content, metadata)
            
            # Generate filename
            job_from = metadata.get('job_from', 'unknown')
            timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
            base_filename = f"career_analysis_{job_from}_{timestamp}"
            
            # Convert to requested format
            if output_format.lower() == 'pdf':
                return self._generate_pdf_from_html(cleaned_html, base_filename)
            elif output_format.lower() in ['word', 'docx']:
                return self._generate_word_from_html(cleaned_html, base_filename)
            else:
                return False, {'error': f'Unsupported output format: {output_format}'}
                
        except Exception as e:
            logger.error(f"Error generating document from HTML: {str(e)}", exc_info=True)
            return False, {'error': f'Document generation failed: {str(e)}'}
    
    def _prepare_html_for_document(self, html_content: str, metadata: Dict[str, Any]) -> str:
        """
        Prepare and clean HTML content for document conversion.
        
        This method:
        1. Extracts clean content from the captured HTML
        2. Removes CSS, JavaScript, and styling
        3. Creates simple, document-friendly HTML
        4. Adds metadata header/footer
        """
        
        # Extract job information for header
        job_from = metadata.get('job_from', 'Unknown')
        analysis_mode = metadata.get('analysis_mode', 'top_matches')
        generated_date = datetime.now().strftime('%B %d, %Y')
        
        # Mode display mapping
        mode_display = {
            'top_matches': 'Discovery Analysis',
            'specific': 'Specific Transition Analysis'
        }.get(analysis_mode, analysis_mode.title())
        
        # Clean the HTML content - remove all styling and extract just text content
        print(f"🔍 Original HTML content length: {len(html_content)}")
        cleaned_content = self._extract_text_content_from_html(html_content)
        print(f"🔍 Cleaned HTML content length: {len(cleaned_content)}")
        
        if len(cleaned_content) < 100:
            print(f"⚠️  WARNING: Cleaned content is very short!")
            print(f"🔍 Cleaned content: {cleaned_content}")
        else:
            print(f"🔍 First 300 chars of cleaned content: {cleaned_content[:300]}")
        
        # Create simple HTML document without complex CSS
        complete_html = f"""
        <!DOCTYPE html>
        <html lang="en">
        <head>
            <meta charset="UTF-8">
            <title>Career Transition Analysis - {job_from}</title>
        </head>
        <body>
            <h1>Career Transition Analysis</h1>
            <p><strong>Job Profile:</strong> {job_from} | <strong>Analysis Type:</strong> {mode_display} | <strong>Generated:</strong> {generated_date}</p>
            <p><em>NAB Skills Intelligence Platform</em></p>
            <hr>
            
            {cleaned_content}
            
            <hr>
            <p><em>Generated by NAB Skills Intelligence Platform on {generated_date}</em></p>
        </body>
        </html>
        """
        
        return complete_html
    
    def _extract_text_content_from_html(self, html_content: str) -> str:
        """Extract clean text content from HTML, preserving structure but removing styling."""
        import re
        
        # Remove style tags and their content completely
        html_content = re.sub(r'<style[^>]*>.*?</style>', '', html_content, flags=re.DOTALL | re.IGNORECASE)
        
        # Remove script tags and their content
        html_content = re.sub(r'<script[^>]*>.*?</script>', '', html_content, flags=re.DOTALL | re.IGNORECASE)
        
        # Remove HTML comments
        html_content = re.sub(r'<!--.*?-->', '', html_content, flags=re.DOTALL)
        
        # Remove complex CSS classes and styling attributes
        html_content = re.sub(r'\s+class="[^"]*"', '', html_content)
        html_content = re.sub(r'\s+style="[^"]*"', '', html_content)
        html_content = re.sub(r'\s+id="[^"]*"', '', html_content)
        
        # Clean up common Tailwind/utility classes that might remain
        html_content = re.sub(r'<div[^>]*>\s*</div>', '', html_content)  # Remove empty divs
        html_content = re.sub(r'<span[^>]*>\s*</span>', '', html_content)  # Remove empty spans
        
        # Convert common HTML elements to simpler versions
        html_content = re.sub(r'<div[^>]*>', '<div>', html_content)
        html_content = re.sub(r'<span[^>]*>', '<span>', html_content)
        html_content = re.sub(r'<p[^>]*>', '<p>', html_content)
        html_content = re.sub(r'<h([1-6])[^>]*>', r'<h\1>', html_content)
        
        # Remove any remaining complex attributes
        html_content = re.sub(r'<([a-zA-Z][a-zA-Z0-9]*)\s+[^>]*>', r'<\1>', html_content)
        
        # Clean up whitespace
        html_content = re.sub(r'\n\s*\n', '\n\n', html_content)
        html_content = re.sub(r'[ \t]+', ' ', html_content)
        
        return html_content.strip()
    
    def _clean_html_content(self, html_content: str) -> str:
        """Clean HTML content for document conversion."""
        
        # Remove script tags and their content
        html_content = re.sub(r'<script\b[^<]*(?:(?!<\/script>)<[^<]*)*<\/script>', '', html_content, flags=re.IGNORECASE)
        
        # Remove interactive elements
        interactive_patterns = [
            r'<button\b[^>]*>.*?</button>',
            r'<input\b[^>]*>',
            r'onclick="[^"]*"',
            r'onchange="[^"]*"',
            r'href="[^"]*"'
        ]
        
        for pattern in interactive_patterns:
            html_content = re.sub(pattern, '', html_content, flags=re.IGNORECASE)
        
        # Remove loading spinners and placeholders
        html_content = re.sub(r'<div[^>]*loading[^>]*>.*?</div>', '', html_content, flags=re.IGNORECASE | re.DOTALL)
        html_content = re.sub(r'<div[^>]*placeholder[^>]*>.*?</div>', '', html_content, flags=re.IGNORECASE | re.DOTALL)
        
        # Clean up extra whitespace
        html_content = re.sub(r'\s+', ' ', html_content)
        html_content = re.sub(r'>\s+<', '><', html_content)
        
        return html_content.strip()
    
    def _generate_document_header(self, job_from: str, mode_display: str, generated_date: str) -> str:
        """Generate document header."""
        return f"""
        <div class="document-header">
            <div class="document-title">Career Transition Analysis</div>
            <div class="document-subtitle">
                Job Profile: {job_from} | Analysis Type: {mode_display} | Generated: {generated_date}
            </div>
            <div class="document-subtitle">
                NAB Skills Intelligence Platform
            </div>
        </div>
        """
    
    def _generate_document_footer(self, generated_date: str) -> str:
        """Generate document footer."""
        return f"""
        <div class="document-footer">
            <div class="footer-content">
                Generated by NAB Skills Intelligence Platform on {generated_date}
            </div>
        </div>
        """
    
    def _get_document_css(self) -> str:
        """Generate CSS styles optimized for document conversion."""
        return """
        @page {
            margin: 2cm;
            size: A4;
        }
        
        body {
            font-family: 'Arial', sans-serif;
            font-size: 11pt;
            line-height: 1.5;
            color: #333;
            margin: 0;
            padding: 0;
        }
        
        .document-container {
            max-width: 100%;
            margin: 0 auto;
        }
        
        .document-header {
            text-align: center;
            margin-bottom: 30px;
            padding-bottom: 20px;
            border-bottom: 2px solid #e53e3e;
        }
        
        .document-title {
            font-size: 24pt;
            font-weight: bold;
            color: #e53e3e;
            margin-bottom: 10px;
        }
        
        .document-subtitle {
            font-size: 12pt;
            color: #666;
            margin-bottom: 5px;
        }
        
        .document-content {
            margin-bottom: 40px;
        }
        
        .document-footer {
            border-top: 1px solid #ddd;
            padding-top: 20px;
            text-align: center;
            font-size: 10pt;
            color: #666;
        }
        
        /* Section styling */
        h1, h2, h3, h4 {
            color: #e53e3e;
            margin-top: 25px;
            margin-bottom: 15px;
        }
        
        h1 { font-size: 18pt; }
        h2 { font-size: 16pt; }
        h3 { font-size: 14pt; }
        h4 { font-size: 12pt; }
        
        /* Remove interactive styling */
        .bg-gradient-to-r,
        .hover\\:bg-gray-50,
        .cursor-pointer,
        .transition-colors {
            background: none !important;
            cursor: default !important;
            transition: none !important;
        }
        
        /* Card styling for document */
        .bg-white {
            background: #fff !important;
            border: 1px solid #ddd !important;
            border-radius: 8px;
            margin-bottom: 20px;
            padding: 15px;
        }
        
        /* Purple headers become simple headers */
        .bg-gradient-to-r.from-purple-600 {
            background: #6b46c1 !important;
            color: white !important;
            padding: 15px;
            border-radius: 8px 8px 0 0;
            margin-bottom: 15px;
        }
        
        /* Text utilities */
        .text-sm { font-size: 10pt; }
        .text-base { font-size: 11pt; }
        .text-lg { font-size: 12pt; }
        .text-xl { font-size: 14pt; }
        .text-2xl { font-size: 16pt; }
        
        .font-medium { font-weight: 500; }
        .font-semibold { font-weight: 600; }
        .font-bold { font-weight: bold; }
        
        /* Spacing */
        .mb-2 { margin-bottom: 8px; }
        .mb-3 { margin-bottom: 12px; }
        .mb-4 { margin-bottom: 16px; }
        .mb-6 { margin-bottom: 24px; }
        
        .mt-2 { margin-top: 8px; }
        .mt-3 { margin-top: 12px; }
        .mt-4 { margin-top: 16px; }
        
        /* Grid layouts become simple blocks */
        .grid {
            display: block !important;
        }
        
        .grid > div {
            margin-bottom: 10px;
        }
        
        /* Hide interactive elements */
        button,
        .fas.fa-times,
        .cursor-pointer,
        [onclick] {
            display: none !important;
        }
        """
    
    def _generate_pdf_from_html(self, html_content: str, base_filename: str) -> Tuple[bool, Dict[str, Any]]:
        """Generate PDF from HTML using weasyprint or reportlab."""
        try:
            # Try weasyprint first (better HTML/CSS support)
            try:
                import weasyprint
                
                # Create temporary HTML file
                temp_html_file = os.path.join(self.temp_dir, f"{base_filename}.html")
                with open(temp_html_file, 'w', encoding='utf-8') as f:
                    f.write(html_content)
                
                # Generate PDF
                pdf_content = weasyprint.HTML(filename=temp_html_file).write_pdf()
                
                # Clean up temp file
                os.unlink(temp_html_file)
                
                return True, {
                    'content': pdf_content,
                    'content_type': 'application/pdf',
                    'filename': f"{base_filename}.pdf",
                    'format': 'PDF'
                }
                
            except ImportError:
                # Fallback to reportlab (more basic but Windows-friendly)
                return self._generate_pdf_with_reportlab(html_content, base_filename)
                
        except Exception as e:
            logger.error(f"Error generating PDF: {str(e)}", exc_info=True)
            return False, {'error': f'PDF generation failed: {str(e)}'}
    
    def _generate_word_from_html(self, html_content: str, base_filename: str) -> Tuple[bool, Dict[str, Any]]:
        """Generate Word document from HTML."""
        try:
            # Try python-docx with html2docx
            try:
                from html2docx import html2docx
                
                # Extract job information for title
                job_from = base_filename.replace('career_analysis_', '').split('_')[0]
                title = f"Career Analysis - {job_from}"
                
                print(f"🔍 HTML-to-Word conversion starting...")
                print(f"🔍 HTML content length: {len(html_content)}")
                print(f"🔍 Title: {title}")
                print(f"🔍 First 500 chars of HTML: {html_content[:500]}")
                
                # DEBUG: Check if HTML contains actual content beyond header
                if len(html_content) < 1000:
                    print(f"⚠️  WARNING: HTML content is very short ({len(html_content)} chars)")
                    print(f"🔍 FULL HTML CONTENT:\n{html_content}")
                else:
                    # Check for key content indicators
                    content_indicators = ['<h1>', '<h2>', '<h3>', '<p>', '<div', '<table', '<ul>', '<ol>']
                    found_indicators = [indicator for indicator in content_indicators if indicator in html_content.lower()]
                    print(f"🔍 Content indicators found: {found_indicators}")
                    
                    # Show more of the content to debug
                    print(f"🔍 First 1500 chars of HTML:\n{html_content[:1500]}")
                
                # Convert HTML to Word with required title parameter
                try:
                    doc_content_stream = html2docx(html_content, title=title)
                    
                    print(f"🔍 Word document generated, type: {type(doc_content_stream)}")
                    
                    # html2docx returns a BytesIO object, we need to extract the bytes
                    if hasattr(doc_content_stream, 'getvalue'):
                        doc_content = doc_content_stream.getvalue()
                        print(f"🔍 Extracted bytes from BytesIO, length: {len(doc_content)}")
                    else:
                        doc_content = doc_content_stream
                        print(f"🔍 Using content directly, type: {type(doc_content)}")
                        
                    if len(doc_content) == 0:
                        print("❌ WARNING: Document content is empty after conversion!")
                        
                except Exception as conversion_error:
                    print(f"❌ html2docx conversion failed: {conversion_error}")
                    print(f"❌ Error type: {type(conversion_error)}")
                    raise conversion_error
                
                return True, {
                    'content': doc_content,
                    'content_type': 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
                    'filename': f"{base_filename}.docx",
                    'format': 'Word'
                }
                
            except ImportError:
                # Fallback: save as RTF (Rich Text Format - opens in Word)
                rtf_content = self._convert_html_to_rtf(html_content)
                
                return True, {
                    'content': rtf_content.encode('utf-8'),
                    'content_type': 'application/rtf',
                    'filename': f"{base_filename}.rtf",
                    'format': 'RTF'
                }
                
        except Exception as e:
            logger.error(f"Error generating Word document: {str(e)}", exc_info=True)
            return False, {'error': f'Word document generation failed: {str(e)}'}
    
    def _generate_pdf_with_reportlab(self, html_content: str, base_filename: str) -> Tuple[bool, Dict[str, Any]]:
        """Generate PDF using reportlab (fallback method)."""
        try:
            from reportlab.lib.pagesizes import letter, A4
            from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer
            from reportlab.lib.styles import getSampleStyleSheet
            from reportlab.lib.units import inch
            from html import unescape
            import io
            
            # Create PDF buffer
            buffer = io.BytesIO()
            doc = SimpleDocTemplate(buffer, pagesize=A4)
            
            # Convert HTML to simple text content
            text_content = self._html_to_text_for_reportlab(html_content)
            
            # Create document
            styles = getSampleStyleSheet()
            story = []
            
            # Add content as paragraphs
            for line in text_content.split('\n'):
                if line.strip():
                    story.append(Paragraph(unescape(line), styles['Normal']))
                    story.append(Spacer(1, 0.1*inch))
            
            doc.build(story)
            pdf_content = buffer.getvalue()
            buffer.close()
            
            return True, {
                'content': pdf_content,
                'content_type': 'application/pdf',
                'filename': f"{base_filename}.pdf",
                'format': 'PDF'
            }
            
        except Exception as e:
            logger.error(f"Error generating PDF with reportlab: {str(e)}", exc_info=True)
            return False, {'error': f'PDF generation with reportlab failed: {str(e)}'}
    
    def _convert_html_to_rtf(self, html_content: str) -> str:
        """Convert HTML to RTF format (fallback for Word)."""
        # Simple HTML to RTF conversion
        # Remove HTML tags and convert to RTF format
        import re
        
        # Extract text content
        text_content = re.sub(r'<[^>]+>', '', html_content)
        text_content = unescape(text_content)
        
        # Create basic RTF document
        rtf_content = r"""{\rtf1\ansi\deff0 {\fonttbl {\f0 Times New Roman;}}
        \f0\fs24 """ + text_content.replace('\n', r'\par ') + r'}'
        
        return rtf_content
    
    def _html_to_text_for_reportlab(self, html_content: str) -> str:
        """Convert HTML to plain text for reportlab."""
        import re
        from html import unescape
        
        # Remove script and style elements
        html_content = re.sub(r'<(script|style)[^>]*>.*?</\1>', '', html_content, flags=re.DOTALL)
        
        # Convert headers to emphasized text
        html_content = re.sub(r'<h[1-6][^>]*>(.*?)</h[1-6]>', r'\n\1\n', html_content)
        
        # Remove HTML tags
        text_content = re.sub(r'<[^>]+>', '', html_content)
        
        # Decode HTML entities
        text_content = unescape(text_content)
        
        # Clean up whitespace
        text_content = re.sub(r'\n\s*\n', '\n\n', text_content)
        text_content = re.sub(r'[ \t]+', ' ', text_content)
        
        return text_content.strip()
